package com.laiso.blogs.model;

import java.io.Serializable;

public class Article implements Serializable {

    private Integer articleId;

    private String articleLabel;

    private Integer articleLikenum;

    private Integer articleSuperarticleid;

    private String articleContent;

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_label
     *
     * @return the value of article.article_label
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public String getArticleLabel() {
        return articleLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_label
     *
     * @param articleLabel the value for article.article_label
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setArticleLabel(String articleLabel) {
        this.articleLabel = articleLabel == null ? null : articleLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_likenum
     *
     * @return the value of article.article_likenum
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public Integer getArticleLikenum() {
        return articleLikenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_likenum
     *
     * @param articleLikenum the value for article.article_likenum
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setArticleLikenum(Integer articleLikenum) {
        this.articleLikenum = articleLikenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_superArticleId
     *
     * @return the value of article.article_superArticleId
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public Integer getArticleSuperarticleid() {
        return articleSuperarticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_superArticleId
     *
     * @param articleSuperarticleid the value for article.article_superArticleId
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setArticleSuperarticleid(Integer articleSuperarticleid) {
        this.articleSuperarticleid = articleSuperarticleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
}