package com.laiso.blogs.model;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.blogsId
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    private Integer blogsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.LikeNum
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    private Integer likenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.blogsId
     *
     * @return the value of blogs.blogsId
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public Integer getBlogsid() {
        return blogsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.blogsId
     *
     * @param blogsid the value for blogs.blogsId
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setBlogsid(Integer blogsid) {
        this.blogsid = blogsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.LikeNum
     *
     * @return the value of blogs.LikeNum
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public Integer getLikenum() {
        return likenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.LikeNum
     *
     * @param likenum the value for blogs.LikeNum
     *
     * @mbg.generated Fri Aug 24 19:07:37 CST 2018
     */
    public void setLikenum(Integer likenum) {
        this.likenum = likenum;
    }
}